name: null
favicon: null
layout_spectrum: 0.73684
typography_spectrum: 0.04386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#848382'
    - '#2e2e2e'
    - '#72d0ff'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
